"""add root_cause table4

Revision ID: 5f06b8d16c8e
Revises: c103a9e6b881
Create Date: 2023-04-12 14:02:04.909590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f06b8d16c8e'
down_revision = 'c103a9e6b881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    op.drop_column('items', 'price')
    op.drop_column('items', 'on_offer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('on_offer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
