"""add root_cause table5

Revision ID: de42d93815f2
Revises: 5f06b8d16c8e
Create Date: 2023-04-12 15:37:53.161833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de42d93815f2'
down_revision = '5f06b8d16c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorials',
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tutorial_id')
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=42, increment=1, minvalue=1, maxvalue=2147483647, cycle=True, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.drop_table('tutorials')
    # ### end Alembic commands ###
